--- SEED
INSERT IGNORE INTO levels [
    {
        id: levels:-2,
        name: "Floor -2",
        ord: -2,
    },
    {
        id: levels:-1,
        name: "Floor -1",
        ord: -1,
    },
    {
        id: levels:1,
        name: "Floor 1",
        ord: 1,
    },
    {
        id: levels:2,
        name: "Floor 2",
        ord: 2,
    },
    {
        id: levels:3,
        name: "Floor 3",
        ord: 3,
    },
    {
        id: levels:roof,
        name: "Roof",
        ord: 4,
    }
];
