INSERT IGNORE INTO electric_rooms [
    {
        name: "-8.7",
        level: levels:-2
    }
];
INSERT IGNORE INTO electric_rooms [
    {
        name: "ТП-1",
        level: levels:-1
    },
    {
        name: "ТП-2",
        level: levels:-1
    },
    {
        name: "ТП-3",
        level: levels:-1
    },
    {
        name: "ТП-4",
        level: levels:-1
    },
    {
        name: "-1.9",
        level: levels:-1
    },
    {
        name: "-1.8",
        level: levels:-1
    },
    {
        name: "-1.6",
        level: levels:-1
    },
];
INSERT IGNORE INTO electric_rooms [
    {
        name: "1.1",
        level: levels:1
    },
    {
        name: "1.2",
        level: levels:1
    },
    {
        name: "1.3",
        level: levels:1
    },
    {
        name: "1.4",
        level: levels:1
    },
    {
        name: "1.5",
        level: levels:1
    },
    {
        name: "1.6",
        level: levels:1
    },
    {
        name: "1.7",
        level: levels:1
    },
];
INSERT IGNORE INTO electric_rooms [
    {
        name: "2.1",
        level: levels:2
    },
    {
        name: "2.2",
        level: levels:2
    },
    {
        name: "2.3",
        level: levels:2
    },
    {
        name: "2.4",
        level: levels:2
    },
    {
        name: "2.5",
        level: levels:2
    },
    {
        name: "2.6",
        level: levels:2
    },
    {
        name: "2.7",
        level: levels:2
    },
];
INSERT IGNORE INTO electric_rooms [
    {
        name: "3.3",
        level: levels:3
    },
    {
        name: "3.5",
        level: levels:3
    },
    {
        name: "3.7",
        level: levels:3
    },
    {
        name: "3а",
        level: levels:3
    },
    {
        name: "3б",
        level: levels:3
    },
];
