// Generated by SurrealKit — do not edit.
// Run `surrealkit typegen` to regenerate.

import type { GeometryMultiLine, GeometryPolygon, RecordId } from 'surrealdb';

export interface AppConfig {
	id: RecordId<'app_config'>;
	edges?: { [key: string]: unknown };
	entities?: { [key: string]: unknown };
	excludeTables?: string[];
	graph?: { [key: string]: unknown };
	map?: { [key: string]: unknown };
	search?: { [key: string]: unknown };
	version: number;
}

export interface Boards {
	id: RecordId<'boards'>;
	name: string;
	room: RecordId<'electric_rooms'>;
}

export interface Breakers {
	id: RecordId<'breakers'>;
	board: RecordId<'boards'>;
	description?: string;
	name: string;
	value?: number;
}

export interface Connects {
	id: RecordId<'connects'>;
	cable?: string;
	in: RecordId<'breakers'> | RecordId<'transformers'>;
	out: RecordId<'breakers'> | RecordId<'rents'>;
}

export interface ElectricRooms {
	id: RecordId<'electric_rooms'>;
	geometry?: GeometryPolygon;
	level: RecordId<'levels'>;
	name: string;
}

export interface EmbeddingQueue {
	id: RecordId<'embedding_queue'>;
	data?: RecordId<'marker_views'>;
	error_message?: string;
	status: 'pending' | 'processing' | 'failed' | 'done';
	updated_at: unknown;
}

export interface Levels {
	id: RecordId<'levels'>;
	geometry?: GeometryMultiLine | GeometryPolygon;
	name: string;
	ord: number;
}

export interface MarkerViews {
	id: RecordId<'marker_views'>;
	generated_description: string;
	image_embedding?: number[];
	image_url?: string;
	marker: RecordId<'markers'>;
	text_embedding?: number[];
	user_description?: string;
}

export interface Markers {
	id: RecordId<'markers'>;
	closes_shop: RecordId<'rents'>;
	level: RecordId<'levels'>;
	zone: RecordId<'zones'>;
}

export interface Rents {
	id: RecordId<'rents'>;
	geometry?: GeometryPolygon;
	level?: RecordId<'levels'>;
	name: string;
}

export interface Rooms {
	id: RecordId<'rooms'>;
	geometry?: GeometryPolygon;
	level?: RecordId<'levels'>;
	name?: string;
}

export interface Shops {
	id: RecordId<'shops'>;
	aliases?: string[];
	area?: RecordId<'rents'>;
	name: string;
}

export interface Transformers {
	id: RecordId<'transformers'>;
	name: string;
	room: RecordId<'electric_rooms'>;
}

export interface Zones {
	id: RecordId<'zones'>;
	geometry: GeometryPolygon;
	level: RecordId<'levels'>;
	name: string;
}
