// Generated by SurrealKit — do not edit.
// Run `surrealkit typegen` to regenerate.

import type { GeometryPoint, GeometryPolygon, RecordId } from 'surrealdb';

export interface AppConfig {
	id: RecordId<'app_config'>;
	edges?: { [key: string]: unknown };
	entities?: { [key: string]: unknown };
	excludeTables?: string[];
	graph?: { [key: string]: unknown };
	map?: { [key: string]: unknown };
	search?: { [key: string]: unknown };
	version: number;
}

export interface Boards {
	id: RecordId<'boards'>;
	name: string;
	room: RecordId<'electric_rooms'>;
}

export interface Breakers {
	id: RecordId<'breakers'>;
	board: RecordId<'boards'>;
	description?: string;
	name: string;
	value?: number;
}

export interface Connects {
	id: RecordId<'connects'>;
	cable?: string;
	in: RecordId<'breakers'>;
	out: RecordId<'breakers'> | RecordId<'rents'>;
}

export interface ElectricRooms {
	id: RecordId<'electric_rooms'>;
	geometry?: GeometryPolygon;
	level: RecordId<'levels'>;
	name: string;
}

export interface Embeddings {
	id: RecordId<'embeddings'>;
	description?: string;
	image?: string;
	image_embedding?: number[];
	marker: GeometryPoint;
	text_embedding?: number[];
}

export interface Levels {
	id: RecordId<'levels'>;
	name: string;
	ord: number;
}

export interface Rents {
	id: RecordId<'rents'>;
	geometry?: GeometryPolygon;
	level?: RecordId<'levels'>;
	name: string;
}

export interface Shops {
	id: RecordId<'shops'>;
	aliases?: string[];
	area?: RecordId<'rents'>;
	name: string;
}

export interface Zones {
	id: RecordId<'zones'>;
	geometry: GeometryPolygon;
	level: RecordId<'levels'>;
	name: string;
}
