export type {
	// Shared unions
	GraphRole,
	GraphHierarchyRole,
	EdgeRole,
	MapUnits,
	MapPlane,
	DiagnosticLevel,
	FieldTypeName,
	// Overlay
	AppConfigOverlay,
	EntityOverlay,
	EntityDisplayOverlay,
	TableSortKeyOverlay,
	FieldOverlay,
	EdgeOverlay,
	GraphNodeOverlay,
	MapLayerOverlay,
	MapOverlay,
	SearchOverlay,
	GraphOverlay,
	GraphLayoutDirection,
	GraphLayoutAlign,
	GraphLayoutSpacingOverlay,
	GraphCompoundPaddingOverlay,
	// AutoProfile
	AutoProfileTableKind,
	AutoProfileField,
	AutoProfileTable,
	AutoProfile,
	TablePermissions,
	SurrealEngineVersion,
	// Resolved
	Diagnostic,
	ResolvedField,
	ResolvedEntityDisplay,
	ResolvedTableSortKey,
	ResolvedEntityGraph,
	ResolvedEntityMap,
	ResolvedEntity,
	ResolvedEdge,
	ResolvedMapLayer,
	ResolvedFloorPlan,
	ResolvedMap,
	ResolvedSearch,
	ResolvedGraph,
	ResolvedGraphLayout,
	ResolvedGraphNode,
	ResolvedConfig,
	ProductView
} from './types';

export { merge, DEFAULT_GRAPH_LAYOUT } from './merge';
export { parseSurrealVersion, engineAtLeast } from './surreal-version';
export {
	OVERLAY_DOC_ID,
	OVERLAY_VERSION,
	emptyOverlay,
	cloneOverlay,
	stringifyOverlay,
	parseOverlayJson,
	softParseOverlay,
	liftOverlayV1toV2,
	overlayV2toV1,
	parseStringList,
	formatStringList,
	parseSortText,
	formatSortText,
	formatDisplayText,
	parseDisplayText,
	sortedKeys,
	type OverlayParseResult
} from './overlay-io';
